package com.example.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Getter
@Setter
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor  // Default constructor is required by AWS DynamoDB SDK
@DynamoDBTable(tableName = "person")
@ToString
public class Person {

    public Person(String id, String name, Integer age) {
        this.id = id;
        this.name = name;
        this.age = age;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "age")
    private Integer age;

    private String status;

    private Map<String,String> map = new HashMap<>();

    List<Person> personList = new ArrayList<>();

    public enum Status {
        New,Old,WOn

    }
    @Getter
    public enum Source {

        COACHBAR("Coachbar");

        String value;

        Source(String value){
            this.value=value;
        }

    }




}
